window.CATALOGO_LOCAL = [
  {
    id: 9001,
    nombre: 'Toyota Supra GR 3.0 Turbo',
    marca: 'Toyota',
    categoria: 'Deportivo',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'Automática',
    color: 'Rojo',
    precio: 385000000,
    precioOriginal: 420000000,
    descuentoPorcentaje: 8,
    stock: 2,
    descripcion:
      'Un coupé que despierta pasiones: motor 6 cilindros turbo, postura baja y un rugido que se siente en el pecho. Perfecto para los fines de semana de carretera abierta.',
    destacado: true,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9002,
    nombre: 'Mazda CX-5 Grand Touring AWD',
    marca: 'Mazda',
    categoria: 'SUV',
    anio: 2023,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'Automática',
    color: 'Blanco perla',
    precio: 148900000,
    precioOriginal: null,
    descuentoPorcentaje: 0,
    stock: 4,
    descripcion:
      'Silencioso, refinado y con acabados que enamoran al tacto. El compañero ideal para la ciudad y para escapar del ruido con la familia.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9003,
    nombre: 'Renault Duster Iconic 4x2',
    marca: 'Renault',
    categoria: 'SUV',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'CVT',
    color: 'Naranja Atacama',
    precio: 112900000,
    precioOriginal: 119900000,
    descuentoPorcentaje: 6,
    stock: 7,
    descripcion:
      'Robusta, aventurera y rendidora. Agarra cualquier camino destapado sin quejarse y te lleva donde los planes se vuelven recuerdos.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9004,
    nombre: 'Chevrolet Onix LTZ Turbo',
    marca: 'Chevrolet',
    categoria: 'Familiar',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'Automática',
    color: 'Azul Glacial',
    precio: 79900000,
    precioOriginal: null,
    descuentoPorcentaje: 0,
    stock: 12,
    descripcion:
      'El sedan que toda familia conoce: ágil, económico y con maletero generoso para las maletas, el mercado y la vida entera.',
    destacado: true,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9005,
    nombre: 'Hyundai Tucson Limited Hybrid',
    marca: 'Hyundai',
    categoria: 'SUV',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Híbrido',
    transmision: 'Automática',
    color: 'Gris Titanio',
    precio: 179900000,
    precioOriginal: null,
    descuentoPorcentaje: 0,
    stock: 3,
    descripcion:
      'Su diseño llama la atención y su consumo híbrido cuida tu bolsillo. Tecnología inteligente para viajes largos en familia.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9006,
    nombre: 'Kia Sportage GT-Line',
    marca: 'Kia',
    categoria: 'SUV',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'Automática',
    color: 'Verde Esmeralda',
    precio: 159900000,
    precioOriginal: 169900000,
    descuentoPorcentaje: 6,
    stock: 5,
    descripcion:
      'Atrevida por fuera, cálida por dentro. Pantalla flotante, asientos cómodos y ese toque premium que se siente apenas cierras la puerta.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9007,
    nombre: 'BMW M4 Competition',
    marca: 'BMW',
    categoria: 'Deportivo',
    anio: 2023,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'Automática',
    color: 'Azul Portimao',
    precio: 469000000,
    precioOriginal: null,
    descuentoPorcentaje: 0,
    stock: 1,
    descripcion:
      'Pura adrenalina alemana. Un deportivo que también sabe ser elegante cuando llegas al restaurante. Solo para quien se atreve a pisar a fondo.',
    destacado: true,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9008,
    nombre: 'Mercedes-Benz Clase C 300 AMG',
    marca: 'Mercedes-Benz',
    categoria: 'Elegante',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'Automática',
    color: 'Negro Obsidiana',
    precio: 389000000,
    precioOriginal: null,
    descuentoPorcentaje: 0,
    stock: 2,
    descripcion:
      'La definición de sofisticación. Interior con luces de ambiente, cuero y una conducción sedosa que convierte cada trayecto en un pequeño lujo.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9009,
    nombre: 'Audi A5 Sportback 45 TFSI',
    marca: 'Audi',
    categoria: 'Elegante',
    anio: 2023,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'Automática',
    color: 'Gris Daytona',
    precio: 315000000,
    precioOriginal: 335000000,
    descuentoPorcentaje: 6,
    stock: 3,
    descripcion:
      'Líneas fluidas que parecen esculpidas por el viento. Deportivo cuando quieres, refinado siempre. Un capricho bien justificado.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1552519507-88aa2dfa9fdb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9010,
    nombre: 'Ford Explorer Limited 4x4',
    marca: 'Ford',
    categoria: 'Familiar',
    anio: 2023,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'Automática',
    color: 'Plata Icónico',
    precio: 279000000,
    precioOriginal: null,
    descuentoPorcentaje: 0,
    stock: 2,
    descripcion:
      'Espacio de sobra para siete y fuerza para cargar el equipaje de todos. La camioneta de las vacaciones y los domingos de picnic.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9011,
    nombre: 'Nissan Frontier Pro-4X',
    marca: 'Nissan',
    categoria: 'Camioneta',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Diésel',
    transmision: 'Automática',
    color: 'Negro Volcánico',
    precio: 219900000,
    precioOriginal: null,
    descuentoPorcentaje: 0,
    stock: 4,
    descripcion:
      'Hecha para trabajar y para el fin de semana. Carga, remolca y no se achica ante un camino difícil. Fuerte donde tiene que serlo.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9012,
    nombre: 'Volkswagen Golf GTI Performance',
    marca: 'Volkswagen',
    categoria: 'Deportivo',
    anio: 2023,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'DSG',
    color: 'Rojo Tornado',
    precio: 215000000,
    precioOriginal: 229000000,
    descuentoPorcentaje: 6,
    stock: 2,
    descripcion:
      'El hot hatch de culto. Práctico como un familiar, divertido como un juguete. La sonrisa al conducir está incluida en el precio.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9013,
    nombre: 'Porsche 911 Carrera S',
    marca: 'Porsche',
    categoria: 'Deportivo',
    anio: 2023,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'PDK',
    color: 'Amarillo Racing',
    precio: 899000000,
    precioOriginal: null,
    descuentoPorcentaje: 0,
    stock: 1,
    descripcion:
      'El sueño atemporal. Icono entre íconos, con esa silueta que nadie más sabe replicar. Una obra de ingeniería para disfrutar sin prisa.',
    destacado: true,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1568844293986-8d0400bd4745?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9014,
    nombre: 'Jeep Wrangler Rubicon',
    marca: 'Jeep',
    categoria: 'SUV',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'Automática',
    color: 'Verde Sarge',
    precio: 329000000,
    precioOriginal: null,
    descuentoPorcentaje: 0,
    stock: 2,
    descripcion:
      'Sin miedo al barro ni a la aventura. Techo abierto, espíritu libre y una capacidad todoterreno que invita a perderse a propósito.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9015,
    nombre: 'Honda CR-V Touring Hybrid',
    marca: 'Honda',
    categoria: 'Familiar',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Híbrido',
    transmision: 'Automática',
    color: 'Blanco Platino',
    precio: 195000000,
    precioOriginal: 205000000,
    descuentoPorcentaje: 5,
    stock: 5,
    descripcion:
      'Confiable como pocas, espaciosa y con consumo amable. La elección sensata que además se siente cálida y bien hecha.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9016,
    nombre: 'Volvo XC60 Recharge T8',
    marca: 'Volvo',
    categoria: 'SUV',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Híbrido enchufable',
    transmision: 'Automática',
    color: 'Azul Denim',
    precio: 345000000,
    precioOriginal: null,
    descuentoPorcentaje: 0,
    stock: 2,
    descripcion:
      'Seguridad de otra liga y un interior nórdico que transmite calma. El equilibrio entre potencia, elegancia y cuidado del planeta.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9017,
    nombre: 'Subaru Forester XT AWD',
    marca: 'Subaru',
    categoria: 'Familiar',
    anio: 2023,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'CVT',
    color: 'Azul Marino',
    precio: 155000000,
    precioOriginal: null,
    descuentoPorcentaje: 0,
    stock: 3,
    descripcion:
      'Tracción total de serie y una visibilidad que da tranquilidad. El aliado de las familias que no le temen a la montaña.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9018,
    nombre: 'Land Rover Defender 110',
    marca: 'Land Rover',
    categoria: 'SUV',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Híbrido',
    transmision: 'Automática',
    color: 'Gris Pangea',
    precio: 429000000,
    precioOriginal: 449000000,
    descuentoPorcentaje: 4,
    stock: 1,
    descripcion:
      'Rugged y a la vez premium. Un todoterreno con alma de expedición que también sabe portarse bien en la ciudad.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9019,
    nombre: 'Cupra Formentor VZ 2.0',
    marca: 'Cupra',
    categoria: 'Deportivo',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'DSG',
    color: 'Cobre',
    precio: 249900000,
    precioOriginal: null,
    descuentoPorcentaje: 0,
    stock: 3,
    descripcion:
      'Diseño que rompe el molde y un temperamento deportivo. Para quienes quieren destacar sin gritar demasiado.',
    destacado: true,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9020,
    nombre: 'BYD Seal Performance AWD',
    marca: 'BYD',
    categoria: 'Eléctrico',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Eléctrico',
    transmision: 'Automática',
    color: 'Azul Atlantis',
    precio: 189900000,
    precioOriginal: 199900000,
    descuentoPorcentaje: 5,
    stock: 6,
    descripcion:
      'Silencio, torque instantáneo y cero gasolina. La nueva era llega con una aceleración que te pega al asiento.',
    destacado: true,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9021,
    nombre: 'Lexus RX 350h Executive',
    marca: 'Lexus',
    categoria: 'Elegante',
    anio: 2024,
    kilometraje: 0,
    combustible: 'Híbrido',
    transmision: 'Automática',
    color: 'Blanco Nieve',
    precio: 359000000,
    precioOriginal: null,
    descuentoPorcentaje: 0,
    stock: 2,
    descripcion:
      'El lujo sereno japonés. Suavidad, fiabilidad y un silencio de cabina que convierte cada viaje en un descanso.',
    destacado: false,
    agotado: false,
    imagenUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9022,
    nombre: 'Chevrolet Camaro SS',
    marca: 'Chevrolet',
    categoria: 'Deportivo',
    anio: 2022,
    kilometraje: 0,
    combustible: 'Gasolina',
    transmision: 'Automática',
    color: 'Negro',
    precio: 289000000,
    precioOriginal: 305000000,
    descuentoPorcentaje: 5,
    stock: 0,
    descripcion:
      'Motor V8 americano con carácter puro. Un muscle car clásico y brutal que ya es parte de la historia del automóvil.',
    destacado: false,
    agotado: true,
    imagenUrl: 'https://images.unsplash.com/photo-1552519507-88aa2dfa9fdb?auto=format&fit=crop&w=800&q=80',
  },
];
